import Signup from './signup';
import Head from 'next/head'
import Script from 'next/script'


export default function Home() {
  


  return (
    <div className="container">
    <Head>
      <title>Array Component</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Signup />
      </div>
    </div>
  );
}