import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react';
import { useRouter } from 'next/router';
import React, { useContext } from 'react';
import DataContext from '../components/DataContext';
import Link from 'next/link';
const axios = require('axios');

export default function Login() {

    const context = useContext(DataContext);
    const router = useRouter();

    // set state for first name, last name
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    
    const [message, setMessage] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const onSubmit = async (e) => {
        e.preventDefault();
        // set message to empty string
        setMessage('');
        setIsLoading(true);
        setEmail(e.target.email.value);
        setPassword(e.target.password.value);
        try {
            const loginData = {
                email: email,
                password,
            }
            const response = await axios.post(
                'http://localhost:8080/login',
                loginData
            );
            if (response.status === 200) {
                localStorage.setItem('userId', response.data.user.id);
                router.push('/workspace');
                setIsLoading(false);
            }
            else {
                setMessage("Invalid Form");
                setIsLoading(false);
            }

        } catch (error) {
            setMessage("Form submission failed");
            setIsLoading(false);
        }
    }

    return (
        <div>
            <Head>
                <title>Workspace</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
                <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>
            </Head>
            <div className="container my-5 p-5">
                <h1 className="text-primary d-flex justify-content-center" >Login</h1>
                <form onSubmit={onSubmit} className="my-5">
                    <div className="row g-3">
                        <div className="row g-3 d-flex justify-content-center">
                            <div className="col-5">
                            <label className="my-2" htmlFor="ssn">Email</label>
                            <input type="text" className="form-control" id="email" name="username" value={email} placeholder='example@domain.com' onChange={(e) => setEmail(e.target.value)} />
                            </div>
                        </div>
                    <div className="row g-3 d-flex justify-content-center">
                        <div className="col-5">
                        <label className="my-2" htmlFor="password">Password</label>
                        <input type="text" className="form-control" id="password1" name="password" placeholder='' value={password} onChange={(e) => setPassword(e.target.value)} />
                        </div>
                    </div>

                        <div className="col-12 d-flex justify-content-center">
                            <button type="submit" className="btn btn-success btn-lg">Submit</button>
                        </div>

                        <div className="col-12 d-flex justify-content-center">
                            <Link href="/signup">
                                <a>No account? Sign up here!</a>
                            </Link>
                        </div>

                        {message && <div className="alert alert-danger">{message}</div>}

                    </div>
                </form>
            </div>
        </div>



    )
}
