import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react';
import { useRouter } from 'next/router';
import { useDataContext } from '../components/DataContext';
import React, { useContext } from 'react';
import Link from 'next/link';

const axios = require('axios');

export default function Signup() {
    const router = useRouter();

    // set state for first name, last name
    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [email, setEmail] = useState('');
    const [username, setUsername] = useState('');
    const [password1, setPassword1] = useState('');
    const [password2, setPassword2] = useState('');

    
    const [message, setMessage] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const isEmailValid = (email) => {
        // Regular expression for a simple email validation
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return emailRegex.test(email);
    };

    const onSubmit = async (e) => {
        e.preventDefault();
        if (password1 !== password2) {
            setMessage("Passwords do not match");
            return;
        }
        if (!isEmailValid(email)) {
            setMessage("Invalid email");
            return;
        }
        setIsLoading(true);
        setFirstName(e.target.firstName.value);
        setLastName(e.target.lastName.value);
        setEmail(e.target.email.value);
        setUsername(e.target.username.value);
        setPassword1(e.target.password1.value);
        setPassword2(e.target.password2.value);
        try {
            const userData = {
                "first_name": firstName,
                "last_name": lastName,
                "email": email,
                "username": username,
                "password": password1
            }
            console.log(userData);
            const response = await axios.post(
                'http://localhost:8080/users',
                userData
            );
            console.log(response);
            // if the http response code is 200, then we have a valid response
            if (response.status === 200) {
                setMessage("Form submitted successfully");             
            }

            else {
                setMessage("Invalid Form");
                setIsLoading(false);
            }

        } catch (error) {
            setMessage("Form submission failed");
            setIsLoading(false);
        }
    }

    return (
        <div>
            <Head>
                <title>Workspace</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
                <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>
            </Head>
            <div className="container my-5 p-5">
                <h1 className="text-primary d-flex justify-content-center" >Signup</h1>
                <form onSubmit={onSubmit} className="my-5">
                    <div className="row g-3">
                        <div className="col-6">
                            <label htmlFor="firstName">First Name</label>
                            <input type="text" className="form-control" id="firstName" name="firstName" placeholder="Thomas" value={firstName} onChange={(e) => setFirstName(e.target.value)} />
                        </div>

                        <div className="col-6">
                        <label htmlFor="lastName">Last Name</label>
                        <input type="text" className="form-control" id="lastName" name="lastName" placeholder="Friedman" value={lastName} onChange={(e) => setLastName(e.target.value)} />
                        </div>

                        <div className="col-6">
                        <label htmlFor="Email">Email</label>
                        <input type="text" className="form-control" id="email" name="email" value={email} placeholder="user@domain.com" onChange={(e) => setEmail(e.target.value)} />
                        </div>

                        <div className="col-6">
                        <label htmlFor="ssn">Username</label>
                        <input type="text" className="form-control" id="username" name="username" value={username} placeholder='Username' onChange={(e) => setUsername(e.target.value)} />
                        </div>

                        <div className="col-6">
                        <label htmlFor="password1">Password</label>
                        <input type="text" className="form-control" id="password1" name="password1" placeholder='' value={password1} onChange={(e) => setPassword1(e.target.value)} />
                        </div>

                        <div className="col-6">
                        <label htmlFor="passowrd2">Confirm Password</label>
                        <input type="text" className="form-control" id="password2" name="password2" placeholder='' value={password2} onChange={(e) => setPassword2(e.target.value)} />
                        </div>

                        <div className="col-12 d-flex justify-content-center">
                            <button type="submit" className="btn btn-success btn-lg">Submit</button>
                        </div>

                        <div className="col-12 d-flex justify-content-center">
                            <Link href="/login">
                                <a>Already have an account?</a>
                            </Link>
                        </div>

                        {message && <div className="alert alert-danger">{message}</div>}

                    </div>
                </form>
            </div>
        </div>



    )
}