import Head from 'next/head'
import Script from 'next/script'
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import DataContext from '../components/DataContext';
import React, { useContext } from 'react';
const axios = require('axios');


export default function Questions() {

    const context = useContext(DataContext);
    const router = useRouter();

    const [message, setMessage] = useState('');
    const [isLoading, setIsLoading] = useState(true);
    const [spaces, setSpaces] = useState([]);

    // before the page loads, get the questions and authToken
    useEffect(() => {
        getWorkspaces();
    }, []);



    const getWorkspaces = async () => {
        try {
            // if userId is in the localStorage, set the userId state
            const userId = localStorage.getItem('userId');
            if (userId) {
                context.setUserId(userId);
            }
    
            const response = await axios.get(
                `http://localhost:8080/get-workspaces?user_id=${userId || context.userId}`
            );
    
            if (response.status === 200) {
                console.log(response.data);
                setSpaces(response.data);
                setIsLoading(false);
            }
        } catch (error) {
            console.log(error);
        }
    };

    const workspaceListView = () => {

        // ... (existing code)
    
        return spaces.map((space, index) => {
            return (
                <div className="item card my-2" key={index}>
                    <style>
                    {`
                .item {
                    cursor: pointer;
                }
                
                .card-body {
                    transition: transform 0.1s ease-in-out; /* Only transition transform property */
                }

                .item:hover .card-body {
                    background-color: #e6e6e6;
                    transform: scale(1.05); /* Scale the card-body on hover */
                }
                `}
                    </style>
                    <div className="card-body d-flex justify-content-between text-center" onClick={() => {
                        localStorage.setItem('workspaceId', space.home_folder_id);
                        context.setWorkspaceId(space.home_folder_id);
                        console.log(context.workspaceId);
                        router.push('/space');
                    }}>
                        <div className="card-title">{space.name}</div>
                    </div>
                </div>
            );
        });
    }
    
    return (
        <div className="container d-flex justify-content-center flex-column my-5">
    <Head>
      <title>Array Component</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>
            <h1 className="text-primary d-flex justify-content-center" >Workspace</h1>
            <div className="d-flex justify-content-center">
                <div className="card" style={{ width: "18rem" }}>
                    <div className="card-body">
                        <h5 className="card-title">Choose workspace</h5>
                        {workspaceListView()}
                    </div>
                </div>
            </div>

        </div>
    )
}
